### ISSUE TITLE
The widget does not work for me!

### ISSUE THREAD

**Issue by exaline-ru** [DieterHolvoet/oc-updatewidget-plugin#1]
The widget does not work for me. After installation in the admin, the widget does not display updated plugins. See screenshots.

![image](https://user-images.githubusercontent.com/46493161/81076863-ded6b980-8ef4-11ea-9b4c-ba835099037d.png)

![image](https://user-images.githubusercontent.com/46493161/81076890-e5653100-8ef4-11ea-9eac-ed237b252217.png)

Also - is it possible to show only updated plugins, and in their absence - nothing needs to be shown at all. Otherwise, a long list does not matter.

**Comment by DieterHolvoet** [comment]
Thanks for letting me know! I'll have a look at that issue in the coming days.
You're right about only showing plugins that need updates, good call. I'll change that as well.

**Comment by DieterHolvoet** [comment]
I added an option in settings and config to hide up-to-date plugins from the widget, as you asked.

Apparently the widget only worked when the new version of the plugin was already downloaded, e.g. when having updated the plugin through Composer. I changed the plugin to check for remote versions as well. Now, when a remote update is available, the _More information_ link will bring you to the updates page in settings. In case the update is already downloaded but not yet installed, clicking _Update now_ will update the plugin immediately (as before).

**Comment by DieterHolvoet** [comment]
This is released in version 1.0.2. Let me know if this works for you, @exaline-ru.

**Comment by exaline-ru** [comment]
Thanks for the useful plugin! Everything is working now.

**Comment by DieterHolvoet** [comment]
You're welcome :)
